#ifndef DD_INTEGRATIONS_AUTOLOADING_H
#define DD_INTEGRATIONS_AUTOLOADING_H
#define AUTOLOADERS \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("ddtrace\\bootstrap", "flushtracershutdown", "DDTrace\\Bootstrap::tracerOnce") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION(NULL, "header", "DDTrace\\Bootstrap::initRootSpan") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION(NULL, "http_response_code", "DDTrace\\Bootstrap::initRootSpan") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION(NULL, "curl_exec", "DDTrace\\Integrations\\Curl\\CurlSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\client", "__construct", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceClientMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\client", "count", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceClientMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\client", "delete", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceClientMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\client", "exists", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceClientMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\client", "explain", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceClientMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\client", "get", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceClientMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\client", "index", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceClientMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\client", "scroll", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceClientMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\client", "search", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceClientMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\client", "update", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceClientMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\serializers\\arraytojsonserializer", "serialize", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceSimpleMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\serializers\\arraytojsonserializer", "deserialize", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceSimpleMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\serializers\\everythingtojsonserializer", "serialize", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceSimpleMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\serializers\\everythingtojsonserializer", "deserialize", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceSimpleMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\serializers\\smartserializer", "serialize", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceSimpleMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\serializers\\smartserializer", "deserialize", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceSimpleMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "analyze", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "clearcache", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "close", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "create", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "delete", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "deletealias", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "deletemapping", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "deletetemplate", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "deletewarmer", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "exists", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "existsalias", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "existstemplate", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "existstype", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "flush", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "getalias", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "getaliases", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "getfieldmapping", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "getmapping", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "getsettings", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "gettemplate", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "getwarmer", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "open", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "optimize", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "putalias", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "putmapping", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "putsettings", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "puttemplate", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "putwarmer", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "recovery", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "refresh", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "segments", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "snapshotindex", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "stats", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "status", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "updatealiases", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\indicesnamespace", "validatequery", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\catnamespace", "aliases", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\catnamespace", "allocation", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\catnamespace", "count", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\catnamespace", "fielddata", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\catnamespace", "health", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\catnamespace", "help", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\catnamespace", "indices", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\catnamespace", "master", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\catnamespace", "nodes", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\catnamespace", "pendingtasks", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\catnamespace", "recovery", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\catnamespace", "shards", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\catnamespace", "threadpool", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\snapshotnamespace", "create", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\snapshotnamespace", "createrepository", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\snapshotnamespace", "delete", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\snapshotnamespace", "deleterepository", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\snapshotnamespace", "get", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\snapshotnamespace", "getrepository", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\snapshotnamespace", "restore", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\snapshotnamespace", "status", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\clusternamespace", "getsettings", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\clusternamespace", "health", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\clusternamespace", "pendingtasks", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\clusternamespace", "putsettings", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\clusternamespace", "reroute", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\clusternamespace", "state", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\clusternamespace", "stats", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\nodesnamespace", "hotthreads", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\nodesnamespace", "info", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\nodesnamespace", "shutdown", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\namespaces\\nodesnamespace", "stats", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::traceNamespaceMethod") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("elasticsearch\\endpoints\\abstractendpoint", "performrequest", "DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("illuminate\\database\\eloquent\\builder", "getmodels", "DDTrace\\Integrations\\Eloquent\\EloquentSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("illuminate\\database\\eloquent\\model", "performinsert", "DDTrace\\Integrations\\Eloquent\\EloquentSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("illuminate\\database\\eloquent\\model", "performupdate", "DDTrace\\Integrations\\Eloquent\\EloquentSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("illuminate\\database\\eloquent\\model", "delete", "DDTrace\\Integrations\\Eloquent\\EloquentSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("illuminate\\database\\eloquent\\model", "destroy", "DDTrace\\Integrations\\Eloquent\\EloquentSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("illuminate\\database\\eloquent\\model", "refresh", "DDTrace\\Integrations\\Eloquent\\EloquentSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("guzzlehttp\\client", "send", "DDTrace\\Integrations\\Guzzle\\GuzzleSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("guzzlehttp\\client", "transfer", "DDTrace\\Integrations\\Guzzle\\GuzzleSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("illuminate\\foundation\\application", "handle", "DDTrace\\Integrations\\Laravel\\LaravelSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("illuminate\\routing\\router", "findroute", "DDTrace\\Integrations\\Laravel\\LaravelSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("illuminate\\routing\\route", "run", "DDTrace\\Integrations\\Laravel\\LaravelSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("symfony\\component\\httpfoundation\\response", "setstatuscode", "DDTrace\\Integrations\\Laravel\\LaravelSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("illuminate\\events\\dispatcher", "fire", "DDTrace\\Integrations\\Laravel\\LaravelSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("illuminate\\view\\view", "render", "DDTrace\\Integrations\\Laravel\\LaravelSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("illuminate\\view\\engines\\compilerengine", "get", "DDTrace\\Integrations\\Laravel\\LaravelSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("illuminate\\foundation\\providerrepository", "load", "DDTrace\\Integrations\\Laravel\\LaravelSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("illuminate\\console\\application", "__construct", "DDTrace\\Integrations\\Laravel\\LaravelSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("symfony\\component\\console\\application", "renderexception", "DDTrace\\Integrations\\Laravel\\LaravelSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("memcached", "add", "DDTrace\\Integrations\\Memcached\\MemcachedSandboxedIntegration::traceCommand") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("memcached", "addbykey", "DDTrace\\Integrations\\Memcached\\MemcachedSandboxedIntegration::traceCommandByKey") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("memcached", "append", "DDTrace\\Integrations\\Memcached\\MemcachedSandboxedIntegration::traceCommand") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("memcached", "appendbykey", "DDTrace\\Integrations\\Memcached\\MemcachedSandboxedIntegration::traceCommandByKey") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("memcached", "decrement", "DDTrace\\Integrations\\Memcached\\MemcachedSandboxedIntegration::traceCommand") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("memcached", "decrementbykey", "DDTrace\\Integrations\\Memcached\\MemcachedSandboxedIntegration::traceCommandByKey") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("memcached", "delete", "DDTrace\\Integrations\\Memcached\\MemcachedSandboxedIntegration::traceCommand") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("memcached", "deletemulti", "DDTrace\\Integrations\\Memcached\\MemcachedSandboxedIntegration::traceMulti") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("memcached", "deletebykey", "DDTrace\\Integrations\\Memcached\\MemcachedSandboxedIntegration::traceCommandByKey") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("memcached", "deletemultibykey", "DDTrace\\Integrations\\Memcached\\MemcachedSandboxedIntegration::traceMultiByKey") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("memcached", "get", "DDTrace\\Integrations\\Memcached\\MemcachedSandboxedIntegration::traceCommand") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("memcached", "getmulti", "DDTrace\\Integrations\\Memcached\\MemcachedSandboxedIntegration::traceMulti") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("memcached", "getbykey", "DDTrace\\Integrations\\Memcached\\MemcachedSandboxedIntegration::traceCommandByKey") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("memcached", "getmultibykey", "DDTrace\\Integrations\\Memcached\\MemcachedSandboxedIntegration::traceMultiByKey") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("memcached", "set", "DDTrace\\Integrations\\Memcached\\MemcachedSandboxedIntegration::traceCommand") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("memcached", "setmulti", "DDTrace\\Integrations\\Memcached\\MemcachedSandboxedIntegration::traceMulti") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("memcached", "setbykey", "DDTrace\\Integrations\\Memcached\\MemcachedSandboxedIntegration::traceCommandByKey") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("memcached", "setmultibykey", "DDTrace\\Integrations\\Memcached\\MemcachedSandboxedIntegration::traceMultiByKey") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("memcached", "increment", "DDTrace\\Integrations\\Memcached\\MemcachedSandboxedIntegration::traceCommand") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("memcached", "incrementbykey", "DDTrace\\Integrations\\Memcached\\MemcachedSandboxedIntegration::traceCommandByKey") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("memcached", "prepend", "DDTrace\\Integrations\\Memcached\\MemcachedSandboxedIntegration::traceCommand") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("memcached", "prependbykey", "DDTrace\\Integrations\\Memcached\\MemcachedSandboxedIntegration::traceCommandByKey") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("memcached", "replace", "DDTrace\\Integrations\\Memcached\\MemcachedSandboxedIntegration::traceCommand") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("memcached", "replacebykey", "DDTrace\\Integrations\\Memcached\\MemcachedSandboxedIntegration::traceCommandByKey") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("memcached", "touch", "DDTrace\\Integrations\\Memcached\\MemcachedSandboxedIntegration::traceCommand") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("memcached", "touchbykey", "DDTrace\\Integrations\\Memcached\\MemcachedSandboxedIntegration::traceCommandByKey") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("memcached", "flush", "DDTrace\\Integrations\\Memcached\\MemcachedSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("memcached", "cas", "DDTrace\\Integrations\\Memcached\\MemcachedSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("memcached", "casbykey", "DDTrace\\Integrations\\Memcached\\MemcachedSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION(NULL, "mysqli_connect", "DDTrace\\Integrations\\Mysqli\\MysqliSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("mysqli", "__construct", "DDTrace\\Integrations\\Mysqli\\MysqliSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION(NULL, "mysqli_real_connect", "DDTrace\\Integrations\\Mysqli\\MysqliSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("mysqli", "real_connect", "DDTrace\\Integrations\\Mysqli\\MysqliSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION(NULL, "mysqli_query", "DDTrace\\Integrations\\Mysqli\\MysqliSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION(NULL, "mysqli_prepare", "DDTrace\\Integrations\\Mysqli\\MysqliSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION(NULL, "mysqli_commit", "DDTrace\\Integrations\\Mysqli\\MysqliSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION(NULL, "mysqli_stmt_execute", "DDTrace\\Integrations\\Mysqli\\MysqliSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION(NULL, "mysqli_stmt_get_result", "DDTrace\\Integrations\\Mysqli\\MysqliSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("mysqli", "query", "DDTrace\\Integrations\\Mysqli\\MysqliSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("mysqli", "prepare", "DDTrace\\Integrations\\Mysqli\\MysqliSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("mysqli", "commit", "DDTrace\\Integrations\\Mysqli\\MysqliSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("mysqli_stmt", "execute", "DDTrace\\Integrations\\Mysqli\\MysqliSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("mysqli_stmt", "get_result", "DDTrace\\Integrations\\Mysqli\\MysqliSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("pdo", "__construct", "DDTrace\\Integrations\\PDO\\PDOSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("pdo", "exec", "DDTrace\\Integrations\\PDO\\PDOSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("pdo", "query", "DDTrace\\Integrations\\PDO\\PDOSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("pdo", "commit", "DDTrace\\Integrations\\PDO\\PDOSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("pdo", "prepare", "DDTrace\\Integrations\\PDO\\PDOSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("pdostatement", "execute", "DDTrace\\Integrations\\PDO\\PDOSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("predis\\client", "__construct", "DDTrace\\Integrations\\Predis\\PredisSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("predis\\client", "connect", "DDTrace\\Integrations\\Predis\\PredisSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("predis\\client", "executecommand", "DDTrace\\Integrations\\Predis\\PredisSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("predis\\client", "executeraw", "DDTrace\\Integrations\\Predis\\PredisSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("predis\\pipeline\\pipeline", "executepipeline", "DDTrace\\Integrations\\Predis\\PredisSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("slim\\app", "__construct", "DDTrace\\Integrations\\Slim\\SlimSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("symfony\\component\\httpkernel\\httpkernel", "__construct", "DDTrace\\Integrations\\Symfony\\SymfonySandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("zend_controller_plugin_broker", "predispatch", "DDTrace\\Integrations\\ZendFramework\\ZendFrameworkSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("zend_controller_plugin_broker", "postdispatch", "DDTrace\\Integrations\\ZendFramework\\ZendFrameworkSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("ci_router", "_set_routing", "DDTrace\\Integrations\\CodeIgniter\\V2\\CodeIgniterSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("requests", "set_certificate_path", "DDTrace\\Integrations\\WordPress\\WordPressSandboxedIntegration::init") \
    AUTOLOAD_DDTRACE_KNOWN_INTEGRATION("yii\\di\\container", "__construct", "DDTrace\\Integrations\\Yii\\YiiSandboxedIntegration::init") \


#endif //DD_INTEGRATIONS_AUTOLOADING_H
